# PARCIAL 3 - ESTEBAN RODRIGUEZ - EXPLORACION Y PREPROCESAMIENTO DE DATOS

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, OneHotEncoder, OrdinalEncoder, PowerTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer
from joblib import dump
from joblib import load

In [ ]:
df = pd.read_csv("/content/bank.csv", delimiter=';')

In [ ]:
df.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no  
2  cellular   16   apr       185         1    330         1  failure  no  
3   unknown    3   jun       199         4     -1         0  unknown  no  
4   unknown    5   may       226         1     -1         0  unknown  no

# 1 Dividir en train y test (random state 42, tamaño de test 0.3). Variable a predecir y - has the client subscribed a term deposit? (binary: &#39;yes&#39;,&#39;no&#39;)


In [ ]:
train, test = train_test_split(df, test_size=0.3, random_state=42)

In [ ]:
# Prediccion de variable y - has the client subscribed a term deposit?
Y_train = train["y"]
Y_train

4153    no
2085    no
1891    no
3611    no
4015    no
        ..
4426    no
466     no
3092    no
3772    no
860     no
Name: y, Length: 3164, dtype: object

# 2 Crear transformación de imputación para cada uno de los tipos de variables.


In [ ]:
# No es necesario una imputacion de datos ya que el DataFrame ya esta limpio.
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3164 entries, 4153 to 860
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        3164 non-null   int64 
 1   job        3164 non-null   object
 2   marital    3164 non-null   object
 3   education  3164 non-null   object
 4   default    3164 non-null   object
 5   balance    3164 non-null   int64 
 6   housing    3164 non-null   object
 7   loan       3164 non-null   object
 8   contact    3164 non-null   object
 9   day        3164 non-null   int64 
 10  month      3164 non-null   object
 11  duration   3164 non-null   int64 
 12  campaign   3164 non-null   int64 
 13  pdays      3164 non-null   int64 
 14  previous   3164 non-null   int64 
 15  poutcome   3164 non-null   object
 16  y          3164 non-null   object
dtypes: int64(7), object(10)
memory usage: 444.9+ KB


In [ ]:
X_train = train

# 3 Probar los respectivos escalados en los datos numéricos(maxMin,Standard, Robust)


In [ ]:
print("MinMaxScaler")
scaler = MinMaxScaler()
X_Scaled = scaler.fit_transform(X_train[["age", "balance", "day","duration", "campaign", "pdays", "previous"]])
X_Scaled

MinMaxScaler


array([[0.33823529, 0.07510737, 0.06666667, ..., 0.08163265, 0.        ,
        0.        ],
       [0.20588235, 0.0573441 , 0.9       , ..., 0.04081633, 0.        ,
        0.        ],
       [0.19117647, 0.08252878, 0.63333333, ..., 0.02040816, 0.        ,
        0.        ],
       ...,
       [0.39705882, 0.07795911, 0.16666667, ..., 0.06122449, 0.42087156,
        0.08333333],
       [0.41176471, 0.07510737, 0.66666667, ..., 0.06122449, 0.        ,
        0.        ],
       [0.57352941, 0.07060643, 0.6       , ..., 0.02040816, 0.        ,
        0.        ]])

In [ ]:
print("StandardScaler")
scaler1 = StandardScaler()
Y_Scaled = scaler1.fit_transform(X_train[["age", "balance", "day","duration", "campaign", "pdays", "previous"]])
Y_Scaled

StandardScaler


array([[ 0.071992  , -0.35011973, -1.59025755, ...,  0.63116678,
        -0.4062146 , -0.31601896],
       [-0.77026116, -0.5392983 ,  1.45896002, ...,  0.03388498,
        -0.4062146 , -0.31601896],
       [-0.86384484, -0.27108188,  0.4832104 , ..., -0.26475592,
        -0.4062146 , -0.31601896],
       ...,
       [ 0.44632674, -0.3197487 , -1.22435145, ...,  0.33252588,
         3.35342197,  0.85206982],
       [ 0.53991042, -0.35011973,  0.6051791 , ...,  0.33252588,
        -0.4062146 , -0.31601896],
       [ 1.56933095, -0.39805473,  0.36124169, ..., -0.26475592,
        -0.4062146 , -0.31601896]])

In [ ]:
print("RobustScaler")
scaler2 = RobustScaler()
Z_Scaled = scaler2.fit_transform(X_train[["age", "balance", "day","duration", "campaign", "pdays", "previous"]])
Z_Scaled

RobustScaler


array([[ 1.87500000e-01, -6.21439669e-03, -1.08333333e+00, ...,
         1.50000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.75000000e-01, -3.63196962e-01,  1.00000000e+00, ...,
         5.00000000e-01,  0.00000000e+00,  0.00000000e+00],
       [-4.37500000e-01,  1.42931124e-01,  3.33333333e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 4.37500000e-01,  5.10961505e-02, -8.33333333e-01, ...,
         1.00000000e+00,  3.67000000e+02,  2.00000000e+00],
       [ 5.00000000e-01, -6.21439669e-03,  4.16666667e-01, ...,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.18750000e+00, -9.66683929e-02,  2.50000000e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

# 4 Determinar la mejor transformación categórica(onehot vs ordinal).


In [ ]:
encoder = OneHotEncoder(sparse=False)
X_train[['single', 'married', 'divorced']] = encoder.fit_transform(X_train[["marital"]])

In [ ]:
encoder.categories_

[array(['divorced', 'married', 'single'], dtype=object)]

In [ ]:
X_train = X_train.drop(["marital"], axis=1)

In [ ]:
X_train.head()

age          job  education default  balance housing loan   contact  \
4153   42   technician  secondary      no      440     yes   no  cellular   
2085   33  blue-collar  secondary      no      -77     yes   no  cellular   
1891   32   management   tertiary      no      656     yes  yes  cellular   
3611   28   technician  secondary      no      389     yes   no  cellular   
4015   36   technician  secondary      no     5902     yes   no   unknown   

      day month  duration  campaign  pdays  previous poutcome   y  single  \
4153    3   feb        13         5     -1         0  unknown  no     0.0   
2085   28   jul       151         3     -1         0  unknown  no     0.0   
1891   20   apr       148         2     -1         0  unknown  no     0.0   
3611   11   may        15         7     -1         0  unknown  no     0.0   
4015   23   may       219         4     -1         0  unknown  no     0.0   

      married  divorced  
4153      1.0       0.0  
2085      1.0       0.0  
1891      0.0       1.0  
3611      0.0       1.0  
4015      1.0       0.0

In [ ]:
ordinal = OrdinalEncoder(categories=[["no", "yes"]])
X_train[["default"]] = ordinal.fit_transform(X_train[["default"]])

In [ ]:
ordinal = OrdinalEncoder(categories=[["no", "yes"]])
X_train[["housing"]] = ordinal.fit_transform(X_train[["housing"]])

In [ ]:
ordinal = OrdinalEncoder(categories=[["no", "yes"]])
X_train[["loan"]] = ordinal.fit_transform(X_train[["loan"]])

In [ ]:
ordinal.categories_

[array(['no', 'yes'], dtype=object)]

In [ ]:
X_train.head()

age          job  education  default  balance  housing  loan   contact  \
4153   42   technician  secondary      0.0      440      1.0   0.0  cellular   
2085   33  blue-collar  secondary      0.0      -77      1.0   0.0  cellular   
1891   32   management   tertiary      0.0      656      1.0   1.0  cellular   
3611   28   technician  secondary      0.0      389      1.0   0.0  cellular   
4015   36   technician  secondary      0.0     5902      1.0   0.0   unknown   

      day month  duration  campaign  pdays  previous poutcome   y  single  \
4153    3   feb        13         5     -1         0  unknown  no     0.0   
2085   28   jul       151         3     -1         0  unknown  no     0.0   
1891   20   apr       148         2     -1         0  unknown  no     0.0   
3611   11   may        15         7     -1         0  unknown  no     0.0   
4015   23   may       219         4     -1         0  unknown  no     0.0   

      married  divorced  
4153      1.0       0.0  
2085      1.0       0.0  
1891      0.0       1.0  
3611      0.0       1.0  
4015      1.0       0.0

# 5 Hacer la distribución de las variables numéricas más Gaussianas.


In [ ]:
# las variables balance, pdays, previous no son aceptadas en el fit_transform por tener datos negativos
pt = PowerTransformer(method="box-cox", standardize=False)
print(pt.fit_transform((train[["age","day","duration","campaign"]].to_numpy())))

[[ 2.57830555  1.67492017  3.16919646  1.04922398]
 [ 2.4665665  13.92301141  7.68754418  0.81413414]
 [ 2.45189208 10.62704177  7.64293962  0.57152603]
 ...
 [ 2.61898924  3.65878317  6.90168587  0.95496794]
 [ 2.62849257 11.05689428  6.10476459  0.95496794]
 [ 2.71916398 10.19113599  7.76025657  0.57152603]]


#6 Crear un pipeline Numérico y otro Categórico. Unir ambos en un solo pipeline usando ColumnTransformer.


In [ ]:
pipeline = Pipeline([("imputar", SimpleImputer(strategy="most_frequent")),
                     ("categorico_a_num", OneHotEncoder(sparse=False))])

In [ ]:
pipeline.fit(X_train[["education"]])

Pipeline(steps=[('imputar', SimpleImputer(strategy='most_frequent')),
                ('categorico_a_num', OneHotEncoder(sparse=False))])

In [ ]:
pipeline.transform(X_train[["education"]])

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [ ]:
pipeline.steps[1][1].categories_

[array(['primary', 'secondary', 'tertiary', 'unknown'], dtype=object)]

In [ ]:
pipeline_numeric = Pipeline([("imputar", SimpleImputer(strategy="mean")),
                     ("escalado", StandardScaler())])

# 7 Seleccionar variables más importantes y eliminar las restantes en el pipeline.


In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3164 entries, 4153 to 860
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        3164 non-null   int64  
 1   job        3164 non-null   object 
 2   education  3164 non-null   object 
 3   default    3164 non-null   float64
 4   balance    3164 non-null   int64  
 5   housing    3164 non-null   float64
 6   loan       3164 non-null   float64
 7   contact    3164 non-null   object 
 8   day        3164 non-null   int64  
 9   month      3164 non-null   object 
 10  duration   3164 non-null   int64  
 11  campaign   3164 non-null   int64  
 12  pdays      3164 non-null   int64  
 13  previous   3164 non-null   int64  
 14  poutcome   3164 non-null   object 
 15  y          3164 non-null   object 
 16  single     3164 non-null   float64
 17  married    3164 non-null   float64
 18  divorced   3164 non-null   float64
dtypes: float64(6), int64(7), object(6)
memory usag

In [ ]:
column_transformer = ColumnTransformer([("Eliminar", "drop", [3,5,6,16,17,18]),
                                       ("Pipeline_numerico", pipeline_numeric, [0,4,8,10,11,12,13]),
                                       ("Pipeline_categorico", pipeline, [1,2,7,9,14])])

In [ ]:
column_transformer.fit(X_train)

ColumnTransformer(transformers=[('Eliminar', 'drop', [3, 5, 6, 16, 17, 18]),
                                ('Pipeline_numerico',
                                 Pipeline(steps=[('imputar', SimpleImputer()),
                                                 ('escalado',
                                                  StandardScaler())]),
                                 [0, 4, 8, 10, 11, 12, 13]),
                                ('Pipeline_categorico',
                                 Pipeline(steps=[('imputar',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('categorico_a_num',
                                                  OneHotEncoder(sparse=False))]),
                                 [1, 2, 7, 9, 14])])

# 8 Utilizar un modelo de RegresionLogística() para predecir la variable: y - has the client subscribed a term deposit? (binary: &#39;yes&#39;,&#39;no&#39;) - Usar validación cruzada de cv=10 y scoring=” accuracy” from sklearn.linear_model import LogisticRegression


In [ ]:
Z_train = column_transformer.transform(X_train)

In [ ]:
resultado = cross_validate(LogisticRegression(), Z_train, Y_train, scoring=["accuracy"], cv=10)

In [ ]:
print("mean={}".format(resultado["test_accuracy"].mean()*100), "std={}".format(resultado["test_accuracy"].std()*100))

mean=90.61234676356668 std=1.0647317209914633


# 9 Iterar el proceso mínimo 2 veces(variando las transformaciones) buscando mejorar el rendimiento.


Transformacion KNNImputer

In [ ]:
pipeline_numeric2 = Pipeline([("imputar", KNNImputer()),
                     ("escalado", StandardScaler())])

In [ ]:
column_transformer2 = ColumnTransformer([("Eliminar", "drop", [3,5,6,16,17,18]),
                                       ("Pipeline_numerico2", pipeline_numeric2, [0,4,8,10,11,12,13]),
                                       ("Pipeline_categorico2", pipeline, [1,2,7,9,14])])

In [ ]:
column_transformer2.fit(X_train)

ColumnTransformer(transformers=[('Eliminar', 'drop', [3, 5, 6, 16, 17, 18]),
                                ('Pipeline_numerico2',
                                 Pipeline(steps=[('imputar', KNNImputer()),
                                                 ('escalado',
                                                  StandardScaler())]),
                                 [0, 4, 8, 10, 11, 12, 13]),
                                ('Pipeline_categorico2',
                                 Pipeline(steps=[('imputar',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('categorico_a_num',
                                                  OneHotEncoder(sparse=False))]),
                                 [1, 2, 7, 9, 14])])

In [ ]:
Z_train = column_transformer2.transform(X_train)

In [ ]:
resultado2 = cross_validate(LogisticRegression(), Z_train, Y_train, scoring=["accuracy"], cv=10)

In [ ]:
print("mean={}".format(resultado2["test_accuracy"].mean()*100), "std={}".format(resultado2["test_accuracy"].std()*100))

mean=90.61234676356668 std=1.0647317209914633


Transformacion IterativeImputer

In [ ]:
pipeline_numeric3 = Pipeline([("imputar", IterativeImputer()),
                     ("escalado", StandardScaler())])

In [ ]:
column_transformer3 = ColumnTransformer([("Eliminar", "drop", [3,5,6,16,17,18]),
                                       ("Pipeline_numerico2", pipeline_numeric3, [0,4,8,10,11,12,13]),
                                       ("Pipeline_categorico2", pipeline, [1,2,7,9,14])])

In [ ]:
column_transformer3.fit(X_train)

ColumnTransformer(transformers=[('Eliminar', 'drop', [3, 5, 6, 16, 17, 18]),
                                ('Pipeline_numerico2',
                                 Pipeline(steps=[('imputar',
                                                  IterativeImputer()),
                                                 ('escalado',
                                                  StandardScaler())]),
                                 [0, 4, 8, 10, 11, 12, 13]),
                                ('Pipeline_categorico2',
                                 Pipeline(steps=[('imputar',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('categorico_a_num',
                                                  OneHotEncoder(sparse=False))]),
                                 [1, 2, 7, 9, 14])])

In [ ]:
Z_train = column_transformer3.transform(X_train)

In [ ]:
resultado3 = cross_validate(LogisticRegression(), Z_train, Y_train, scoring=["accuracy"], cv=10)

In [ ]:
print("mean={}".format(resultado3["test_accuracy"].mean()*100), "std={}".format(resultado3["test_accuracy"].std()*100))

mean=90.61234676356668 std=1.0647317209914633


# 10 Guardar el pipeline como joblib.


In [ ]:
dump(column_transformer, "Parcial3_EDRA.joblib")

['Parcial3_EDRA.joblib']

# 11 Cargar el pipeline y probarlo con un dato de entrada.

In [ ]:
sd=load('Parcial3_EDRA.joblib')

In [ ]:
age = 42#@param {type:"number"}
job ="technician" #@param "{type:string}"
education ="secondary" #@param "{type:string}"
default = 0.0 #@param "{type:float}"
balance = 440 #@param {type:"number"}
housing = 1.0 #@param "{type:float}"
loan = 0.0 #@param "{type:float}"
contract = "cellular" #@param "{type:string}"
day =3 #@param {type:"number"}
month = "feb" #@param "{type:string}"
duration = 13 #@param {type:"number"}
compaign = 5 #@param {type:"number"}
pdays = -1 #@param {type:"number"}
previous = 0 #@param {type:"number"}
poutcome = "unknown" #@param "{type:string}"
y ="no" #@param "{type:string}"
single = 0.0 #@param "{type:float}"
married = 1.0 #@param "{type:float}"
divorced = 0.0 #@param "{type:float}"
